Adds a simple WRR scheduler
obonaventure/draft-schedulers pull request #17
Opened 2020-05-12 10:14 UTC by mpiraux

2020-05-12 15:17 UTC, markusa requested changes

2020-05-12 15:17 UTC, markusa commented on draft-schedulers.mkd
> +            self.last_idx = (self.last_idx + 1) % len(self.distribution)
Can `self.last_idx = (self.last_idx + 1) % len(self.distribution)` be shifted after checking the block state?

Effectively it does not change the modus operandi but would reduce useless computing power. Furthermore it is according to the RR implementation.

2020-05-12 15:21 UTC, obonaventure approved these changes

2020-05-12 15:21 UTC, obonaventure commented on draft-schedulers.mkd
> +over the ones whose congestion window is open.
Could add a note saying that a deficit variant is possible as well to take packet length into account.

2020-05-13 13:03 UTC, markusa approved these changes

2020-05-14 08:45 UTC, merged